# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
name: test-coverage
permissions:
  contents: write # Required for the BYOB action
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage
          
      - name: Test coverage
        id: coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          print(cov)
          
          # Calculate coverage percentage
          coverage_pct <- covr::percent_coverage(cov)
          coverage_rounded <- round(coverage_pct, 2)
          
          # Output the coverage value for the next steps
          cat("::set-output name=coverage::", coverage_rounded, "%\n", sep="")
          
          # Create Cobertura XML for potential future use
          covr::to_cobertura(cov)
        shell: Rscript {0}
      
      - name: Determine badge color
        id: badge_color
        run: |
          COVERAGE=$(echo ${{ steps.coverage.outputs.coverage }} | cut -d. -f1 | cut -d% -f1)
          if [ $COVERAGE -lt 50 ]; then
            echo "::set-output name=color::red"
          elif [ $COVERAGE -lt 70 ]; then
            echo "::set-output name=color::orange"
          elif [ $COVERAGE -lt 80 ]; then
            echo "::set-output name=color::yellow"
          elif [ $COVERAGE -lt 90 ]; then
            echo "::set-output name=color::yellowgreen"
          elif [ $COVERAGE -lt 100 ]; then
            echo "::set-output name=color::green"
          else
            echo "::set-output name=color::brightgreen"
          fi
        
      - name: Create coverage badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: coverage
          LABEL: 'coverage'
          STATUS: ${{ steps.coverage.outputs.coverage }}
          COLOR: ${{ steps.badge_color.outputs.color }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
        
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package